### ISSUE TITLE
mobile version doesnt work

### ISSUE THREAD

**Issue by kaenydsgn** [subwaymatch/typefolio#2]
everything works fine on every device and every resolution. but not on mobile phones.. and that only in portrait modus in landscape everything works..

[http://mobiletest.me/iphone_5_emulator/?u=http://kaeny.de](url)

**Comment by subwaymatch** [comment]
Hi Kaeny. 

In your typegrid.css, the width for .container seems to be missing. 

``` css
@media screen and (max-width: 767px) {
  .container {
    width: 280px;
  }
```

Thanks, 
Park
