### ISSUE TITLE
Remove padding/width limits on mobile

### ISSUE THREAD

**Issue by yarnball** [subwaymatch/typefolio#4]
Hi,

Great work on this!

On mobile/small screens, it limits the width of the content significantly. It makes it illegible.

Simple changing the width for `content` in CSS causes elements to move all over the place.

How do I correctly change the width? Thanks

**Comment by subwaymatch** [comment]
Change `width` or `padding` properties in typegrid.css. 
Look for `/* Mobile - Portrait */` section. 

```
/* Mobile - Portrait */
@media screen and (max-width: 767px) {
  .container {
    width: 280px;
  }
```

**Comment by yarnball** [comment]
Thank you but that doesn't work as it puts everything off center. I tried making it 90% width

**Comment by gusparedes** [comment]
Hi
I'm using typefolio for a personal project and i love it!
But i have a problem with responsive menu breakpoint. I want to change the brakpoint i can't find the way

**Comment by subwaymatch** [comment]
In your style.css, please refer to the following sections. 

```css
/* Mobile Menu */
#menu-mobile-wrapper { display: none; }

@media screen and (max-width: 767px) { 
	#menu-mobile-wrapper { display: block; }
}
```
