### ISSUE TITLE
Problem with menu breakpoint

### ISSUE THREAD

**Issue by gusparedes** [subwaymatch/typefolio#6]
Hi
I'm using typefolio for a personal project and i love it!
But i have a problem with responsive menu breakpoint. I want to change the brakpoint i can't find the way

**Comment by subwaymatch** [comment]
In your style.css, please refer to the following sections. 

```css
/* Mobile Menu */
#menu-mobile-wrapper { display: none; }

@media screen and (max-width: 767px) { 
	#menu-mobile-wrapper { display: block; }
}
```
